### ISSUE TITLE
Error: Table has inconsistent number of columns. Do you want fill = TRUE?

### ISSUE THREAD

**Issue by gbganalyst** [feddelegrand7/ralger#2]
I tried to use {ralger} to reproduce what was done at `https://www.r-bloggers.com/scrape-html-table-using-rvest/`.

```r
library(ralger)
library(tidyverse)

df <- table_scrap("https://en.wikipedia.org/wiki/List_of_highest-grossing_films_in_the_United_States_and_Canada", choose = 1)
```

`ralger::table_scrap()` threw this Error: Table has inconsistent number of columns. Do you want fill = TRUE? with no useful guide to solve this for a novice.

I tried to add `fill = TRUE` in 

```r
table_scrap <- function (link, choose = 1, header = T, askRobot = FALSE) 
{
  if (askRobot) {
    if (paths_allowed(link) == TRUE) {
      message(green("It's ok you're allowed to scrap this web page"))
    }
    else {
      message(bgRed("WARNING: you're not allowed to scrap this web page"))
    }
  }
  table <- link %>% read_html() %>% html_table(header, fill = TRUE) %>% 
    purrr::pluck(choose)
  return(table)
}
```
 and it works

```r
table_scrap("https://en.wikipedia.org/wiki/List_of_highest-grossing_films_in_the_United_States_and_Canada")
```

**Comment by feddelegrand7** [comment]
Hi @gbganalyst, 

Thank you very much for alerting me about this error. Now it's fixed (in the development version), I'll submit the fixed version to CRAN asap. Do you mind if I add you as a contributor (ctb) to the package (I'd need your name and family name if possible :) ) ?  

Regards.

**Comment by gbganalyst** [comment]
Thank you so much for this opportunity. My name is Ezekiel Adebayo and my family name is Ogundepo. I can also be reached at gbganalyst@gmail.com or https://bit.ly/gbganalyst.

**Comment by feddelegrand7** [comment]
Sure thanks again !
