### ISSUE TITLE
scraping problems

### ISSUE THREAD

**Issue by vech2000** [feddelegrand7/ralger#3]
does not make spaces when it combines text from different cells of an HTML table

link <- "https://hh.ru/resume/df2e58c6000023b5100039ed1f736563726574?query=hr&source=search"
node <- '.resume-wrapper'
scrap(link, node, clean=TRUE)

**Comment by feddelegrand7** [comment]
hi, could please provide a screen shot of the CSS element chosen on the website ?

**Comment by vech2000** [comment]
![image](https://user-images.githubusercontent.com/59181006/71380744-7d671b80-25e1-11ea-9eaf-73681cb9138b.png)

**Comment by feddelegrand7** [comment]
This way you're extracting all the information of the web page. You'll have one vector of one big element. Try to use other tags in order to get a formatted table.
