### ISSUE TITLE
Is it possible to download data from market.cboe.com with ralger?

### ISSUE THREAD

**Issue by SamoPP** [feddelegrand7/ralger#6]
Hi,

ralger looks very promising.

I was wondering whether there is any way to download data from [http://markets.cboe.com/us/futures/market_statistics/historical_data/](http://markets.cboe.com/us/futures/market_statistics/historical_data/) using ralger?

I mean, let's say I want to download all links if I select _"VX+VXT- Cboe Volatility Index (VX) Futures, Includes TAS"_ from the dropdown. I can then see a list of links grouped by year. Selecting first one really downloads the file if I do this in browser. However if I copy the link and use `read.csv("http://markets.cboe.com/us/futures/market_statistics/historical_data/products/csv/VX/2021-01-20/CFE_VX_F1.csv")` it fails. Is there a trick in ralger that can accomplish successful download?

```
> data <- read.csv("http://markets.cboe.com/us/futures/market_statistics/historical_data/products/csv/VX/2021-01-20/CFE_VX_F1.csv")
Error in file(file, "rt") : 
  cannot open the connection to 'http://markets.cboe.com/us/futures/market_statistics/historical_data/products/csv/VX/2021-01-20/CFE_VX_F1.csv'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'http://markets.cboe.com/us/futures/market_statistics/historical_data/products/csv/VX/2021-01-20/CFE_VX_F1.csv': HTTP status was '404 Not Found'
```
Any other suggestions welcome (Python or whatever).

Thanks.

**Comment by feddelegrand7** [comment]
Hi, 

This is not related to {ralger} which deals with extracting web elements (not csv files), however I've the tried following and it worked : 

`readr::read_csv("http://markets.cboe.com/us/futures/market_statistics/historical_data/products/csv/VX/2021-01-20/")
`
Best.
