### ISSUE TITLE
Extract Href Attributes from Given Nodes

### ISSUE THREAD

**Issue by canholyavkin** [feddelegrand7/ralger#9]
How can I extract the href attributes from given nodes? Is there a ralger alternative for html_attr() of rvest? 

weblink_scrap() extracts all links and in some cases string filtering parameter may not be enough.

**Comment by feddelegrand7** [comment]
Interesting question, for now there is no equivalent that works similarly to html_httr(), but I'll definitely think about it. Anything precise in mind ?

**Comment by canholyavkin** [comment]
Thank you for your interest in this issue.

I wanted to extract specific `href` features from particular page under specific node. However, I couldn't manage to extract those just using `weblink_scrap()`. You may add parameters to `weblink_scrap()` to focus just given nodes, maybe?

**Comment by feddelegrand7** [comment]
`weblink_scrap()` download all the `href` attributes from all anchor tags, maybe I'll try to come up with a particular function that focus on attributes.

**Comment by canholyavkin** [comment]
Instead of adding `node=` parameter to `weblink_scrap()`, it would be better to add `attr=` to other functions, such as `scrap()`, `table_scrap()`. It would be more suitable to tidy approach.

**Comment by feddelegrand7** [comment]
I definitely love the idea, thank you !.  Will implement it ASAP. In the meantime, if you want to create a PR don't hesitate.

**Comment by feddelegrand7** [comment]
Hi @canholyavkin I've added a new function called "attribute_scrap" I'd appreciate it if you could test it, so that I can close this issue. The function is available in the development form of the package. Here an example: 

```
link <- "https://ropensci.org/"
#scraping the class attributes' names from all the anchor
attribute_scrap(link = link, node = "a", attr = "class")

```
Best.

**Comment by canholyavkin** [comment]
It's working like a charm. I've tested in multiple sites and different attributes. 

Thank you for such an awesome package. :)

**Comment by feddelegrand7** [comment]
Thanks for the helpful idea !
